/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './shared.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/forms/src/directives';
import * as import4 from '@angular/forms/src/form_providers';
import * as import5 from 'ng2-bootstrap/components/typeahead/typeahead.module';
import * as import6 from '@angular/common/src/localization';
import * as import7 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import8 from 'ng2-bootstrap/components/utils/components-helper.service';
import * as import9 from '@angular/core/src/di/injector';
import * as import10 from '../../node_modules/ng2-bootstrap/components/typeahead/typeahead-container.component.ngfactory';
import * as import11 from '@angular/core/src/i18n/tokens';
import * as import12 from '@angular/core/src/application_ref';
class SharedModuleInjector extends import0.NgModuleInjector<import1.SharedModule> {
  _CommonModule_0:import2.CommonModule;
  _InternalFormsSharedModule_1:import3.InternalFormsSharedModule;
  _FormsModule_2:import4.FormsModule;
  _TypeaheadModule_3:import5.TypeaheadModule;
  _SharedModule_4:import1.SharedModule;
  __NgLocalization_5:import6.NgLocaleLocalization;
  __RadioControlRegistry_6:import7.RadioControlRegistry;
  __ComponentsHelper_7:import8.ComponentsHelper;
  constructor(parent:import9.Injector) {
    super(parent,[import10.TypeaheadContainerComponentNgFactory],([] as any[]));
  }
  get _NgLocalization_5():import6.NgLocaleLocalization {
    if ((this.__NgLocalization_5 == null)) { (this.__NgLocalization_5 = new import6.NgLocaleLocalization(this.parent.get(import11.LOCALE_ID))); }
    return this.__NgLocalization_5;
  }
  get _RadioControlRegistry_6():import7.RadioControlRegistry {
    if ((this.__RadioControlRegistry_6 == null)) { (this.__RadioControlRegistry_6 = new import7.RadioControlRegistry()); }
    return this.__RadioControlRegistry_6;
  }
  get _ComponentsHelper_7():import8.ComponentsHelper {
    if ((this.__ComponentsHelper_7 == null)) { (this.__ComponentsHelper_7 = new import8.ComponentsHelper(this.parent.get(import12.ApplicationRef),this,this)); }
    return this.__ComponentsHelper_7;
  }
  createInternal():import1.SharedModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._InternalFormsSharedModule_1 = new import3.InternalFormsSharedModule();
    this._FormsModule_2 = new import4.FormsModule();
    this._TypeaheadModule_3 = new import5.TypeaheadModule();
    this._SharedModule_4 = new import1.SharedModule();
    return this._SharedModule_4;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_1; }
    if ((token === import4.FormsModule)) { return this._FormsModule_2; }
    if ((token === import5.TypeaheadModule)) { return this._TypeaheadModule_3; }
    if ((token === import1.SharedModule)) { return this._SharedModule_4; }
    if ((token === import6.NgLocalization)) { return this._NgLocalization_5; }
    if ((token === import7.RadioControlRegistry)) { return this._RadioControlRegistry_6; }
    if ((token === import8.ComponentsHelper)) { return this._ComponentsHelper_7; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const SharedModuleNgFactory:import0.NgModuleFactory<import1.SharedModule> = new import0.NgModuleFactory(SharedModuleInjector,import1.SharedModule);