/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './relative-picker.component';
import * as import1 from '@angular/core/src/change_detection/change_detection';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import9 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import10 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import11 from '../../node_modules/@angular/forms/src/directives/select_control_value_accessor.ngfactory';
import * as import12 from '../../node_modules/@angular/forms/src/directives/select_multiple_control_value_accessor.ngfactory';
import * as import13 from '@angular/core/src/linker/element_ref';
import * as import14 from '@angular/forms/src/directives/default_value_accessor';
import * as import15 from '@angular/forms/src/directives/control_value_accessor';
import * as import16 from '@angular/forms/src/directives/ng_model';
import * as import17 from '@angular/forms/src/directives/ng_control';
import * as import18 from '@angular/forms/src/directives/ng_control_status';
import * as import19 from '@angular/forms/src/directives/select_control_value_accessor';
import * as import20 from '@angular/forms/src/directives/select_multiple_control_value_accessor';
export class Wrapper_RelativePickerComponent {
  /*private*/ _eventHandler:Function;
  context:import0.RelativePickerComponent;
  /*private*/ _changed:boolean;
  /*private*/ _changes:{[key: string]:any};
  /*private*/ _expr_0:any;
  subscription0:any;
  constructor() {
    this._changed = false;
    this._changes = {};
    this.context = new import0.RelativePickerComponent();
    this._expr_0 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    (this.subscription0 && this.subscription0.unsubscribe());
  }
  check_model(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.model = currValue;
      this._changes['model'] = new import1.SimpleChange(this._expr_0,currValue);
      this._expr_0 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if (changed) {
      this.context.ngOnChanges(this._changes);
      this._changes = {};
    } }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any,emit0:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.modelChange.subscribe(_eventHandler.bind(view,'modelChange'))); }
  }
}
var renderType_RelativePickerComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_RelativePickerComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.RelativePickerComponent>;
  _RelativePickerComponent_0_3:Wrapper_RelativePickerComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_RelativePickerComponent_Host0,renderType_RelativePickerComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'kairos-relativepicker',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_RelativePickerComponent0(this.viewUtils,this,0,this._el_0);
    this._RelativePickerComponent_0_3 = new Wrapper_RelativePickerComponent();
    this.compView_0.create(this._RelativePickerComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._RelativePickerComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.RelativePickerComponent) && (0 === requestNodeIndex))) { return this._RelativePickerComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._RelativePickerComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._RelativePickerComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const RelativePickerComponentNgFactory:import7.ComponentFactory<import0.RelativePickerComponent> = new import7.ComponentFactory<import0.RelativePickerComponent>('kairos-relativepicker',View_RelativePickerComponent_Host0,import0.RelativePickerComponent);
const styles_RelativePickerComponent:any[] = ['.form-control[disabled][_ngcontent-%COMP%] {\n        cursor: default;\n    }'];
var renderType_RelativePickerComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.Emulated,styles_RelativePickerComponent,{});
export class View_RelativePickerComponent0 extends import2.AppView<import0.RelativePickerComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _DefaultValueAccessor_3_3:import8.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_3_4:any[];
  _NgModel_3_5:import9.Wrapper_NgModel;
  _NgControl_3_6:any;
  _NgControlStatus_3_7:import10.Wrapper_NgControlStatus;
  _text_4:any;
  _el_5:any;
  _SelectControlValueAccessor_5_3:import11.Wrapper_SelectControlValueAccessor;
  _NG_VALUE_ACCESSOR_5_4:any[];
  _NgModel_5_5:import9.Wrapper_NgModel;
  _NgControl_5_6:any;
  _NgControlStatus_5_7:import10.Wrapper_NgControlStatus;
  _text_6:any;
  _el_7:any;
  _NgSelectOption_7_3:import11.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_7_4:import12.Wrapper_NgSelectMultipleOption;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _NgSelectOption_10_3:import11.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_10_4:import12.Wrapper_NgSelectMultipleOption;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _NgSelectOption_13_3:import11.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_13_4:import12.Wrapper_NgSelectMultipleOption;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _NgSelectOption_16_3:import11.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_16_4:import12.Wrapper_NgSelectMultipleOption;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _NgSelectOption_19_3:import11.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_19_4:import12.Wrapper_NgSelectMultipleOption;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _NgSelectOption_22_3:import11.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_22_4:import12.Wrapper_NgSelectMultipleOption;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _NgSelectOption_25_3:import11.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_25_4:import12.Wrapper_NgSelectMultipleOption;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_RelativePickerComponent0,renderType_RelativePickerComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','input-group'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_1,'input',new import3.InlineArray8(8,'aria-label','...','class','form-control','style','width:50px;margin-right:-1px;','type','text'),(null as any));
    this._DefaultValueAccessor_3_3 = new import8.Wrapper_DefaultValueAccessor(this.renderer,new import13.ElementRef(this._el_3));
    this._NG_VALUE_ACCESSOR_3_4 = [this._DefaultValueAccessor_3_3.context];
    this._NgModel_3_5 = new import9.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_3_4);
    this._NgControl_3_6 = this._NgModel_3_5.context;
    this._NgControlStatus_3_7 = new import10.Wrapper_NgControlStatus(this._NgControl_3_6);
    this._text_4 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_1,'select',new import3.InlineArray4(4,'class','form-control','style','width:inherit'),(null as any));
    this._SelectControlValueAccessor_5_3 = new import11.Wrapper_SelectControlValueAccessor(this.renderer,new import13.ElementRef(this._el_5));
    this._NG_VALUE_ACCESSOR_5_4 = [this._SelectControlValueAccessor_5_3.context];
    this._NgModel_5_5 = new import9.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_5_4);
    this._NgControl_5_6 = this._NgModel_5_5.context;
    this._NgControlStatus_5_7 = new import10.Wrapper_NgControlStatus(this._NgControl_5_6);
    this._text_6 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'option',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgSelectOption_7_3 = new import11.Wrapper_NgSelectOption(new import13.ElementRef(this._el_7),this.renderer,this._SelectControlValueAccessor_5_3.context);
    this._NgSelectMultipleOption_7_4 = new import12.Wrapper_NgSelectMultipleOption(new import13.ElementRef(this._el_7),this.renderer,(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'Years',(null as any));
    this._text_9 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_5,'option',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgSelectOption_10_3 = new import11.Wrapper_NgSelectOption(new import13.ElementRef(this._el_10),this.renderer,this._SelectControlValueAccessor_5_3.context);
    this._NgSelectMultipleOption_10_4 = new import12.Wrapper_NgSelectMultipleOption(new import13.ElementRef(this._el_10),this.renderer,(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'Months',(null as any));
    this._text_12 = this.renderer.createText(this._el_5,'\n			',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_5,'option',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgSelectOption_13_3 = new import11.Wrapper_NgSelectOption(new import13.ElementRef(this._el_13),this.renderer,this._SelectControlValueAccessor_5_3.context);
    this._NgSelectMultipleOption_13_4 = new import12.Wrapper_NgSelectMultipleOption(new import13.ElementRef(this._el_13),this.renderer,(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'Weeks',(null as any));
    this._text_15 = this.renderer.createText(this._el_5,'\n			',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_5,'option',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgSelectOption_16_3 = new import11.Wrapper_NgSelectOption(new import13.ElementRef(this._el_16),this.renderer,this._SelectControlValueAccessor_5_3.context);
    this._NgSelectMultipleOption_16_4 = new import12.Wrapper_NgSelectMultipleOption(new import13.ElementRef(this._el_16),this.renderer,(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'Days',(null as any));
    this._text_18 = this.renderer.createText(this._el_5,'\n      		',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_5,'option',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgSelectOption_19_3 = new import11.Wrapper_NgSelectOption(new import13.ElementRef(this._el_19),this.renderer,this._SelectControlValueAccessor_5_3.context);
    this._NgSelectMultipleOption_19_4 = new import12.Wrapper_NgSelectMultipleOption(new import13.ElementRef(this._el_19),this.renderer,(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'Hours',(null as any));
    this._text_21 = this.renderer.createText(this._el_5,'\n			',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_5,'option',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgSelectOption_22_3 = new import11.Wrapper_NgSelectOption(new import13.ElementRef(this._el_22),this.renderer,this._SelectControlValueAccessor_5_3.context);
    this._NgSelectMultipleOption_22_4 = new import12.Wrapper_NgSelectMultipleOption(new import13.ElementRef(this._el_22),this.renderer,(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'Minutes',(null as any));
    this._text_24 = this.renderer.createText(this._el_5,'\n			',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_5,'option',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgSelectOption_25_3 = new import11.Wrapper_NgSelectOption(new import13.ElementRef(this._el_25),this.renderer,this._SelectControlValueAccessor_5_3.context);
    this._NgSelectMultipleOption_25_4 = new import12.Wrapper_NgSelectMultipleOption(new import13.ElementRef(this._el_25),this.renderer,(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'Seconds',(null as any));
    this._text_27 = this.renderer.createText(this._el_5,'\n    	',(null as any));
    this._text_28 = this.renderer.createText(this._el_1,'\n		',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_1,'input',new import3.InlineArray16(12,'aria-label','...','class','form-control','disabled','','style','width:50px;margin-left:-1px;','type','text','value','ago'),(null as any));
    this._text_30 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._text_31 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_3,new import3.InlineArray8(8,'ngModelChange',(null as any),'keyup',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_3));
    this._NgModel_3_5.subscribe(this,this.eventHandler(this.handleEvent_3),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_5,new import3.InlineArray8(6,'ngModelChange',(null as any),'change',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_5));
    this._NgModel_5_5.subscribe(this,this.eventHandler(this.handleEvent_5),true);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31
    ]
    ),[
      disposable_0,
      disposable_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.DefaultValueAccessor) && (3 === requestNodeIndex))) { return this._DefaultValueAccessor_3_3.context; }
    if (((token === import15.NG_VALUE_ACCESSOR) && (3 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_3_4; }
    if (((token === import16.NgModel) && (3 === requestNodeIndex))) { return this._NgModel_3_5.context; }
    if (((token === import17.NgControl) && (3 === requestNodeIndex))) { return this._NgControl_3_6; }
    if (((token === import18.NgControlStatus) && (3 === requestNodeIndex))) { return this._NgControlStatus_3_7.context; }
    if (((token === import19.NgSelectOption) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._NgSelectOption_7_3.context; }
    if (((token === import20.NgSelectMultipleOption) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._NgSelectMultipleOption_7_4.context; }
    if (((token === import19.NgSelectOption) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._NgSelectOption_10_3.context; }
    if (((token === import20.NgSelectMultipleOption) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._NgSelectMultipleOption_10_4.context; }
    if (((token === import19.NgSelectOption) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._NgSelectOption_13_3.context; }
    if (((token === import20.NgSelectMultipleOption) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._NgSelectMultipleOption_13_4.context; }
    if (((token === import19.NgSelectOption) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._NgSelectOption_16_3.context; }
    if (((token === import20.NgSelectMultipleOption) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._NgSelectMultipleOption_16_4.context; }
    if (((token === import19.NgSelectOption) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._NgSelectOption_19_3.context; }
    if (((token === import20.NgSelectMultipleOption) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._NgSelectMultipleOption_19_4.context; }
    if (((token === import19.NgSelectOption) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._NgSelectOption_22_3.context; }
    if (((token === import20.NgSelectMultipleOption) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._NgSelectMultipleOption_22_4.context; }
    if (((token === import19.NgSelectOption) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._NgSelectOption_25_3.context; }
    if (((token === import20.NgSelectMultipleOption) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._NgSelectMultipleOption_25_4.context; }
    if (((token === import19.SelectControlValueAccessor) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._SelectControlValueAccessor_5_3.context; }
    if (((token === import15.NG_VALUE_ACCESSOR) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._NG_VALUE_ACCESSOR_5_4; }
    if (((token === import16.NgModel) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._NgModel_5_5.context; }
    if (((token === import17.NgControl) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._NgControl_5_6; }
    if (((token === import18.NgControlStatus) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._NgControlStatus_5_7.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DefaultValueAccessor_3_3.ngDoCheck(this,this._el_3,throwOnChange);
    const currVal_3_1_0:any = this.context.model.value;
    this._NgModel_3_5.check_model(currVal_3_1_0,throwOnChange,false);
    this._NgModel_3_5.ngDoCheck(this,this._el_3,throwOnChange);
    this._NgControlStatus_3_7.ngDoCheck(this,this._el_3,throwOnChange);
    this._SelectControlValueAccessor_5_3.ngDoCheck(this,this._el_5,throwOnChange);
    const currVal_5_1_0:any = this.context.model.unit;
    this._NgModel_5_5.check_model(currVal_5_1_0,throwOnChange,false);
    this._NgModel_5_5.ngDoCheck(this,this._el_5,throwOnChange);
    this._NgControlStatus_5_7.ngDoCheck(this,this._el_5,throwOnChange);
    const currVal_7_0_0:any = 'years';
    this._NgSelectOption_7_3.check_value(currVal_7_0_0,throwOnChange,false);
    this._NgSelectOption_7_3.ngDoCheck(this,this._el_7,throwOnChange);
    const currVal_7_1_0:any = 'years';
    this._NgSelectMultipleOption_7_4.check_value(currVal_7_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_7_4.ngDoCheck(this,this._el_7,throwOnChange);
    const currVal_10_0_0:any = 'months';
    this._NgSelectOption_10_3.check_value(currVal_10_0_0,throwOnChange,false);
    this._NgSelectOption_10_3.ngDoCheck(this,this._el_10,throwOnChange);
    const currVal_10_1_0:any = 'months';
    this._NgSelectMultipleOption_10_4.check_value(currVal_10_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_10_4.ngDoCheck(this,this._el_10,throwOnChange);
    const currVal_13_0_0:any = 'weeks';
    this._NgSelectOption_13_3.check_value(currVal_13_0_0,throwOnChange,false);
    this._NgSelectOption_13_3.ngDoCheck(this,this._el_13,throwOnChange);
    const currVal_13_1_0:any = 'weeks';
    this._NgSelectMultipleOption_13_4.check_value(currVal_13_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_13_4.ngDoCheck(this,this._el_13,throwOnChange);
    const currVal_16_0_0:any = 'days';
    this._NgSelectOption_16_3.check_value(currVal_16_0_0,throwOnChange,false);
    this._NgSelectOption_16_3.ngDoCheck(this,this._el_16,throwOnChange);
    const currVal_16_1_0:any = 'days';
    this._NgSelectMultipleOption_16_4.check_value(currVal_16_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_16_4.ngDoCheck(this,this._el_16,throwOnChange);
    const currVal_19_0_0:any = 'hours';
    this._NgSelectOption_19_3.check_value(currVal_19_0_0,throwOnChange,false);
    this._NgSelectOption_19_3.ngDoCheck(this,this._el_19,throwOnChange);
    const currVal_19_1_0:any = 'hours';
    this._NgSelectMultipleOption_19_4.check_value(currVal_19_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_19_4.ngDoCheck(this,this._el_19,throwOnChange);
    const currVal_22_0_0:any = 'minutes';
    this._NgSelectOption_22_3.check_value(currVal_22_0_0,throwOnChange,false);
    this._NgSelectOption_22_3.ngDoCheck(this,this._el_22,throwOnChange);
    const currVal_22_1_0:any = 'minutes';
    this._NgSelectMultipleOption_22_4.check_value(currVal_22_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_22_4.ngDoCheck(this,this._el_22,throwOnChange);
    const currVal_25_0_0:any = 'seconds';
    this._NgSelectOption_25_3.check_value(currVal_25_0_0,throwOnChange,false);
    this._NgSelectOption_25_3.ngDoCheck(this,this._el_25,throwOnChange);
    const currVal_25_1_0:any = 'seconds';
    this._NgSelectMultipleOption_25_4.check_value(currVal_25_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_25_4.ngDoCheck(this,this._el_25,throwOnChange);
    this._NgControlStatus_3_7.checkHost(this,this,this._el_3,throwOnChange);
    this._NgControlStatus_5_7.checkHost(this,this,this._el_5,throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_3_5.ngOnDestroy();
    this._NgSelectOption_7_3.ngOnDestroy();
    this._NgSelectMultipleOption_7_4.ngOnDestroy();
    this._NgSelectOption_10_3.ngOnDestroy();
    this._NgSelectMultipleOption_10_4.ngOnDestroy();
    this._NgSelectOption_13_3.ngOnDestroy();
    this._NgSelectMultipleOption_13_4.ngOnDestroy();
    this._NgSelectOption_16_3.ngOnDestroy();
    this._NgSelectMultipleOption_16_4.ngOnDestroy();
    this._NgSelectOption_19_3.ngOnDestroy();
    this._NgSelectMultipleOption_19_4.ngOnDestroy();
    this._NgSelectOption_22_3.ngOnDestroy();
    this._NgSelectMultipleOption_22_4.ngOnDestroy();
    this._NgSelectOption_25_3.ngOnDestroy();
    this._NgSelectMultipleOption_25_4.ngOnDestroy();
    this._NgModel_5_5.ngOnDestroy();
  }
  handleEvent_3(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_3_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.model.value = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'keyup')) {
      const pd_sub_1:any = ((<any>this.context.modelChange.emit(this.context.model)) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
  handleEvent_5(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._SelectControlValueAccessor_5_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.model.unit = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'change')) {
      const pd_sub_1:any = ((<any>this.context.modelChange.emit(this.context.model)) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
}