/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './time-range.component';
import * as import1 from '@angular/core/src/change_detection/change_detection';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/core/src/linker/view_container';
import * as import9 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import10 from '@angular/core/src/linker/template_ref';
import * as import11 from '@angular/common/src/directives/ng_if';
import * as import12 from '../../node_modules/ng2-bootstrap/components/buttons/button-radio.directive.ngfactory';
import * as import13 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import14 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import15 from '../shared/typeahead.component';
import * as import16 from '../shared/typeahead.component.ngfactory';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from 'ng2-bootstrap/components/buttons/button-radio.directive';
import * as import19 from '@angular/forms/src/directives/control_value_accessor';
import * as import20 from '@angular/forms/src/directives/ng_model';
import * as import21 from '@angular/forms/src/directives/ng_control';
import * as import22 from '@angular/forms/src/directives/ng_control_status';
import * as import23 from './datetime-picker.component';
import * as import24 from './datetime-picker.component.ngfactory';
import * as import25 from './relative-picker.component';
import * as import26 from './relative-picker.component.ngfactory';
export class Wrapper_TimeRangeComponent {
  /*private*/ _eventHandler:Function;
  context:import0.TimeRangeComponent;
  /*private*/ _changed:boolean;
  /*private*/ _changes:{[key: string]:any};
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  subscription0:any;
  subscription1:any;
  subscription2:any;
  subscription3:any;
  subscription4:any;
  constructor() {
    this._changed = false;
    this._changes = {};
    this.context = new import0.TimeRangeComponent();
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
    this._expr_2 = import1.UNINITIALIZED;
    this._expr_3 = import1.UNINITIALIZED;
    this._expr_4 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    (this.subscription0 && this.subscription0.unsubscribe());
    (this.subscription1 && this.subscription1.unsubscribe());
    (this.subscription2 && this.subscription2.unsubscribe());
    (this.subscription3 && this.subscription3.unsubscribe());
    (this.subscription4 && this.subscription4.unsubscribe());
  }
  check_timezone(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.timezone = currValue;
      this._changes['timezone'] = new import1.SimpleChange(this._expr_0,currValue);
      this._expr_0 = currValue;
    }
  }
  check_startRelative(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.startRelative = currValue;
      this._changes['startRelative'] = new import1.SimpleChange(this._expr_1,currValue);
      this._expr_1 = currValue;
    }
  }
  check_startAbsolute(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_2,currValue))) {
      this._changed = true;
      this.context.startAbsolute = currValue;
      this._changes['startAbsolute'] = new import1.SimpleChange(this._expr_2,currValue);
      this._expr_2 = currValue;
    }
  }
  check_endRelative(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_3,currValue))) {
      this._changed = true;
      this.context.endRelative = currValue;
      this._changes['endRelative'] = new import1.SimpleChange(this._expr_3,currValue);
      this._expr_3 = currValue;
    }
  }
  check_endAbsolute(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_4,currValue))) {
      this._changed = true;
      this.context.endAbsolute = currValue;
      this._changes['endAbsolute'] = new import1.SimpleChange(this._expr_4,currValue);
      this._expr_4 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if (changed) {
      this.context.ngOnChanges(this._changes);
      this._changes = {};
    } }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any,emit0:boolean,emit1:boolean,emit2:boolean,emit3:boolean,emit4:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.timezoneChange.subscribe(_eventHandler.bind(view,'timezoneChange'))); }
    if (emit1) { (this.subscription1 = this.context.startRelativeChange.subscribe(_eventHandler.bind(view,'startRelativeChange'))); }
    if (emit2) { (this.subscription2 = this.context.startAbsoluteChange.subscribe(_eventHandler.bind(view,'startAbsoluteChange'))); }
    if (emit3) { (this.subscription3 = this.context.endRelativeChange.subscribe(_eventHandler.bind(view,'endRelativeChange'))); }
    if (emit4) { (this.subscription4 = this.context.endAbsoluteChange.subscribe(_eventHandler.bind(view,'endAbsoluteChange'))); }
  }
}
var renderType_TimeRangeComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_TimeRangeComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.TimeRangeComponent>;
  _TimeRangeComponent_0_3:Wrapper_TimeRangeComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_TimeRangeComponent_Host0,renderType_TimeRangeComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'kairos-timerange',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_TimeRangeComponent0(this.viewUtils,this,0,this._el_0);
    this._TimeRangeComponent_0_3 = new Wrapper_TimeRangeComponent();
    this.compView_0.create(this._TimeRangeComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._TimeRangeComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.TimeRangeComponent) && (0 === requestNodeIndex))) { return this._TimeRangeComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._TimeRangeComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._TimeRangeComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const TimeRangeComponentNgFactory:import7.ComponentFactory<import0.TimeRangeComponent> = new import7.ComponentFactory<import0.TimeRangeComponent>('kairos-timerange',View_TimeRangeComponent_Host0,import0.TimeRangeComponent);
const styles_TimeRangeComponent:any[] = ['td[_ngcontent-%COMP%] {\n    padding-top: 5px;\n    padding-bottom: 5px;\n  }\n\n  tr[_ngcontent-%COMP%] {\n    padding: 5px 5px;\n  }\n\n  .picker-col[_ngcontent-%COMP%]   *[_ngcontent-%COMP%] {\n    display: inline-flex;\n  }\n\n  .timezone-col[_ngcontent-%COMP%] {\n    width: 190px;\n  }\n\n  .label-col[_ngcontent-%COMP%] {\n    width: 50px;\n  }\n\n  .select-col[_ngcontent-%COMP%] {\n    width: 170px;\n  }\n  \n  span[_ngcontent-%COMP%] {\n    display: block;\n    text-align: left;\n  }\n\n  table[_ngcontent-%COMP%] {\n    width: 100%;\n  }'];
var renderType_TimeRangeComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.Emulated,styles_TimeRangeComponent,{});
export class View_TimeRangeComponent0 extends import2.AppView<import0.TimeRangeComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _anchor_8:any;
  /*private*/ _vc_8:import8.ViewContainer;
  _TemplateRef_8_5:any;
  _NgIf_8_6:import9.Wrapper_NgIf;
  _text_9:any;
  _anchor_10:any;
  /*private*/ _vc_10:import8.ViewContainer;
  _TemplateRef_10_5:any;
  _NgIf_10_6:import9.Wrapper_NgIf;
  _text_11:any;
  _text_12:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_TimeRangeComponent0,renderType_TimeRangeComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','panel panel-primary'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','panel-heading'),(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_2,'h4',new import3.InlineArray2(2,'class','panel-title'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'Time range',(null as any));
    this._text_5 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','panel-body'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n',(null as any));
    this._anchor_8 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._vc_8 = new import8.ViewContainer(8,6,this,this._anchor_8);
    this._TemplateRef_8_5 = new import10.TemplateRef_(this,8,this._anchor_8);
    this._NgIf_8_6 = new import9.Wrapper_NgIf(this._vc_8.vcRef,this._TemplateRef_8_5);
    this._text_9 = this.renderer.createText(this._el_6,'\n\n',(null as any));
    this._anchor_10 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._vc_10 = new import8.ViewContainer(10,6,this,this._anchor_10);
    this._TemplateRef_10_5 = new import10.TemplateRef_(this,10,this._anchor_10);
    this._NgIf_10_6 = new import9.Wrapper_NgIf(this._vc_10.vcRef,this._TemplateRef_10_5);
    this._text_11 = this.renderer.createText(this._el_6,'\n\n',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._anchor_8,
      this._text_9,
      this._anchor_10,
      this._text_11,
      this._text_12
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.TemplateRef) && (8 === requestNodeIndex))) { return this._TemplateRef_8_5; }
    if (((token === import11.NgIf) && (8 === requestNodeIndex))) { return this._NgIf_8_6.context; }
    if (((token === import10.TemplateRef) && (10 === requestNodeIndex))) { return this._TemplateRef_10_5; }
    if (((token === import11.NgIf) && (10 === requestNodeIndex))) { return this._NgIf_10_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_8_0_0:any = this.context.componentValid;
    this._NgIf_8_6.check_ngIf(currVal_8_0_0,throwOnChange,false);
    this._NgIf_8_6.ngDoCheck(this,this._anchor_8,throwOnChange);
    const currVal_10_0_0:boolean = !this.context.componentValid;
    this._NgIf_10_6.check_ngIf(currVal_10_0_0,throwOnChange,false);
    this._NgIf_10_6.ngDoCheck(this,this._anchor_10,throwOnChange);
    this._vc_8.detectChangesInNestedViews(throwOnChange);
    this._vc_10.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_8.destroyNestedViews();
    this._vc_10.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 8)) { return new View_TimeRangeComponent1(this.viewUtils,this,8,this._anchor_8,this._vc_8); }
    if ((nodeIndex == 10)) { return new View_TimeRangeComponent6(this.viewUtils,this,10,this._anchor_10,this._vc_10); }
    return (null as any);
  }
}
class View_TimeRangeComponent1 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _ButtonRadioDirective_12_3:import12.Wrapper_ButtonRadioDirective;
  _NG_VALUE_ACCESSOR_12_4:any[];
  _NgModel_12_5:import13.Wrapper_NgModel;
  _NgControl_12_6:any;
  _NgControlStatus_12_7:import14.Wrapper_NgControlStatus;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _ButtonRadioDirective_15_3:import12.Wrapper_ButtonRadioDirective;
  _NG_VALUE_ACCESSOR_15_4:any[];
  _NgModel_15_5:import13.Wrapper_NgModel;
  _NgControl_15_6:any;
  _NgControlStatus_15_7:import14.Wrapper_NgControlStatus;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _anchor_21:any;
  /*private*/ _vc_21:import8.ViewContainer;
  _TemplateRef_21_5:any;
  _NgIf_21_6:import9.Wrapper_NgIf;
  _text_22:any;
  _anchor_23:any;
  /*private*/ _vc_23:import8.ViewContainer;
  _TemplateRef_23_5:any;
  _NgIf_23_6:import9.Wrapper_NgIf;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  compView_28:import2.AppView<import15.TypeaheadComponent>;
  _TypeaheadComponent_28_3:import16.Wrapper_TypeaheadComponent;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _el_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _ButtonRadioDirective_42_3:import12.Wrapper_ButtonRadioDirective;
  _NG_VALUE_ACCESSOR_42_4:any[];
  _NgModel_42_5:import13.Wrapper_NgModel;
  _NgControl_42_6:any;
  _NgControlStatus_42_7:import14.Wrapper_NgControlStatus;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _ButtonRadioDirective_45_3:import12.Wrapper_ButtonRadioDirective;
  _NG_VALUE_ACCESSOR_45_4:any[];
  _NgModel_45_5:import13.Wrapper_NgModel;
  _NgControl_45_6:any;
  _NgControlStatus_45_7:import14.Wrapper_NgControlStatus;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _anchor_52:any;
  /*private*/ _vc_52:import8.ViewContainer;
  _TemplateRef_52_5:any;
  _NgIf_52_6:import9.Wrapper_NgIf;
  _text_53:any;
  _anchor_54:any;
  /*private*/ _vc_54:import8.ViewContainer;
  _TemplateRef_54_5:any;
  _NgIf_54_6:import9.Wrapper_NgIf;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import8.ViewContainer) {
    super(View_TimeRangeComponent1,renderType_TimeRangeComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'table',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'tbody',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_2,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n	',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_3,'td',new import3.InlineArray2(2,'class','label-col'),(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_5,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Start',(null as any));
    this._text_8 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_3,'td',new import3.InlineArray2(2,'class','select-col'),(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_9,'div',new import3.InlineArray2(2,'class','btn-group'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_10,'label',new import3.InlineArray4(4,'btnRadio','Absolute','class','btn btn-default'),(null as any));
    this._ButtonRadioDirective_12_3 = new import12.Wrapper_ButtonRadioDirective(new import17.ElementRef(this._el_12));
    this._NG_VALUE_ACCESSOR_12_4 = [this._ButtonRadioDirective_12_3.context];
    this._NgModel_12_5 = new import13.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_12_4);
    this._NgControl_12_6 = this._NgModel_12_5.context;
    this._NgControlStatus_12_7 = new import14.Wrapper_NgControlStatus(this._NgControl_12_6);
    this._text_13 = this.renderer.createText(this._el_12,'Absolute',(null as any));
    this._text_14 = this.renderer.createText(this._el_10,'\n		',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_10,'label',new import3.InlineArray4(4,'btnRadio','Relative','class','btn btn-default'),(null as any));
    this._ButtonRadioDirective_15_3 = new import12.Wrapper_ButtonRadioDirective(new import17.ElementRef(this._el_15));
    this._NG_VALUE_ACCESSOR_15_4 = [this._ButtonRadioDirective_15_3.context];
    this._NgModel_15_5 = new import13.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_15_4);
    this._NgControl_15_6 = this._NgModel_15_5.context;
    this._NgControlStatus_15_7 = new import14.Wrapper_NgControlStatus(this._NgControl_15_6);
    this._text_16 = this.renderer.createText(this._el_15,'Relative',(null as any));
    this._text_17 = this.renderer.createText(this._el_10,'\n	 ',(null as any));
    this._text_18 = this.renderer.createText(this._el_3,'\n\n	',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_3,'td',new import3.InlineArray2(2,'class','picker-col'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'\n		',(null as any));
    this._anchor_21 = this.renderer.createTemplateAnchor(this._el_19,(null as any));
    this._vc_21 = new import8.ViewContainer(21,19,this,this._anchor_21);
    this._TemplateRef_21_5 = new import10.TemplateRef_(this,21,this._anchor_21);
    this._NgIf_21_6 = new import9.Wrapper_NgIf(this._vc_21.vcRef,this._TemplateRef_21_5);
    this._text_22 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._anchor_23 = this.renderer.createTemplateAnchor(this._el_19,(null as any));
    this._vc_23 = new import8.ViewContainer(23,19,this,this._anchor_23);
    this._TemplateRef_23_5 = new import10.TemplateRef_(this,23,this._anchor_23);
    this._NgIf_23_6 = new import9.Wrapper_NgIf(this._vc_23.vcRef,this._TemplateRef_23_5);
    this._text_24 = this.renderer.createText(this._el_19,'\n	',(null as any));
    this._text_25 = this.renderer.createText(this._el_3,'\n	',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_3,'td',new import3.InlineArray4(4,'class','timezone-col','rowspan','2'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'\n		',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_26,'kairos-typeahead',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_28 = new import16.View_TypeaheadComponent0(this.viewUtils,this,28,this._el_28);
    this._TypeaheadComponent_28_3 = new import16.Wrapper_TypeaheadComponent();
    this._text_29 = this.renderer.createText((null as any),'\n		',(null as any));
    this.compView_28.create(this._TypeaheadComponent_28_3.context);
    this._text_30 = this.renderer.createText(this._el_26,'\n	  ',(null as any));
    this._text_31 = this.renderer.createText(this._el_3,'\n',(null as any));
    this._text_32 = this.renderer.createText(this._el_2,'\n\n',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_2,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'\n	',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_33,'td',new import3.InlineArray2(2,'class','label-col'),(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_35,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'Stop',(null as any));
    this._text_38 = this.renderer.createText(this._el_33,'\n    ',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_33,'td',new import3.InlineArray2(2,'class','select-col'),(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_39,'div',new import3.InlineArray2(2,'class','btn-group'),(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'\n        ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_40,'label',new import3.InlineArray8(6,'btnRadio','Absolute','class','btn btn-default','uncheckable',''),(null as any));
    this._ButtonRadioDirective_42_3 = new import12.Wrapper_ButtonRadioDirective(new import17.ElementRef(this._el_42));
    this._NG_VALUE_ACCESSOR_42_4 = [this._ButtonRadioDirective_42_3.context];
    this._NgModel_42_5 = new import13.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_42_4);
    this._NgControl_42_6 = this._NgModel_42_5.context;
    this._NgControlStatus_42_7 = new import14.Wrapper_NgControlStatus(this._NgControl_42_6);
    this._text_43 = this.renderer.createText(this._el_42,'Absolute',(null as any));
    this._text_44 = this.renderer.createText(this._el_40,'\n		',(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_40,'label',new import3.InlineArray8(6,'btnRadio','Relative','class','btn btn-default','uncheckable',''),(null as any));
    this._ButtonRadioDirective_45_3 = new import12.Wrapper_ButtonRadioDirective(new import17.ElementRef(this._el_45));
    this._NG_VALUE_ACCESSOR_45_4 = [this._ButtonRadioDirective_45_3.context];
    this._NgModel_45_5 = new import13.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_45_4);
    this._NgControl_45_6 = this._NgModel_45_5.context;
    this._NgControlStatus_45_7 = new import14.Wrapper_NgControlStatus(this._NgControl_45_6);
    this._text_46 = this.renderer.createText(this._el_45,'Relative',(null as any));
    this._text_47 = this.renderer.createText(this._el_40,'\n		',(null as any));
    this._text_48 = this.renderer.createText(this._el_40,'\n	 ',(null as any));
    this._text_49 = this.renderer.createText(this._el_33,'\n\n	',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_33,'td',new import3.InlineArray2(2,'class','picker-col'),(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'\n		',(null as any));
    this._anchor_52 = this.renderer.createTemplateAnchor(this._el_50,(null as any));
    this._vc_52 = new import8.ViewContainer(52,50,this,this._anchor_52);
    this._TemplateRef_52_5 = new import10.TemplateRef_(this,52,this._anchor_52);
    this._NgIf_52_6 = new import9.Wrapper_NgIf(this._vc_52.vcRef,this._TemplateRef_52_5);
    this._text_53 = this.renderer.createText(this._el_50,'\n        ',(null as any));
    this._anchor_54 = this.renderer.createTemplateAnchor(this._el_50,(null as any));
    this._vc_54 = new import8.ViewContainer(54,50,this,this._anchor_54);
    this._TemplateRef_54_5 = new import10.TemplateRef_(this,54,this._anchor_54);
    this._NgIf_54_6 = new import9.Wrapper_NgIf(this._vc_54.vcRef,this._TemplateRef_54_5);
    this._text_55 = this.renderer.createText(this._el_50,'\n	',(null as any));
    this._text_56 = this.renderer.createText(this._el_33,'\n',(null as any));
    this._text_57 = this.renderer.createText(this._el_2,'\n\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_12,new import3.InlineArray4(4,'ngModelChange',(null as any),'click',(null as any)),this.eventHandler(this.handleEvent_12));
    this._NgModel_12_5.subscribe(this,this.eventHandler(this.handleEvent_12),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_15,new import3.InlineArray4(4,'ngModelChange',(null as any),'click',(null as any)),this.eventHandler(this.handleEvent_15));
    this._NgModel_15_5.subscribe(this,this.eventHandler(this.handleEvent_15),true);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_28,new import3.InlineArray4(4,'typeaheadOnSelect',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_28));
    this._TypeaheadComponent_28_3.subscribe(this,this.eventHandler(this.handleEvent_28),false,false,false,true,true);
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_42,new import3.InlineArray4(4,'ngModelChange',(null as any),'click',(null as any)),this.eventHandler(this.handleEvent_42));
    this._NgModel_42_5.subscribe(this,this.eventHandler(this.handleEvent_42),true);
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_45,new import3.InlineArray4(4,'ngModelChange',(null as any),'click',(null as any)),this.eventHandler(this.handleEvent_45));
    this._NgModel_45_5.subscribe(this,this.eventHandler(this.handleEvent_45),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._anchor_21,
      this._text_22,
      this._anchor_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._anchor_52,
      this._text_53,
      this._anchor_54,
      this._text_55,
      this._text_56,
      this._text_57
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.ButtonRadioDirective) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._ButtonRadioDirective_12_3.context; }
    if (((token === import19.NG_VALUE_ACCESSOR) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._NG_VALUE_ACCESSOR_12_4; }
    if (((token === import20.NgModel) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._NgModel_12_5.context; }
    if (((token === import21.NgControl) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._NgControl_12_6; }
    if (((token === import22.NgControlStatus) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._NgControlStatus_12_7.context; }
    if (((token === import18.ButtonRadioDirective) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._ButtonRadioDirective_15_3.context; }
    if (((token === import19.NG_VALUE_ACCESSOR) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._NG_VALUE_ACCESSOR_15_4; }
    if (((token === import20.NgModel) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._NgModel_15_5.context; }
    if (((token === import21.NgControl) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._NgControl_15_6; }
    if (((token === import22.NgControlStatus) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._NgControlStatus_15_7.context; }
    if (((token === import10.TemplateRef) && (21 === requestNodeIndex))) { return this._TemplateRef_21_5; }
    if (((token === import11.NgIf) && (21 === requestNodeIndex))) { return this._NgIf_21_6.context; }
    if (((token === import10.TemplateRef) && (23 === requestNodeIndex))) { return this._TemplateRef_23_5; }
    if (((token === import11.NgIf) && (23 === requestNodeIndex))) { return this._NgIf_23_6.context; }
    if (((token === import15.TypeaheadComponent) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._TypeaheadComponent_28_3.context; }
    if (((token === import18.ButtonRadioDirective) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._ButtonRadioDirective_42_3.context; }
    if (((token === import19.NG_VALUE_ACCESSOR) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._NG_VALUE_ACCESSOR_42_4; }
    if (((token === import20.NgModel) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._NgModel_42_5.context; }
    if (((token === import21.NgControl) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._NgControl_42_6; }
    if (((token === import22.NgControlStatus) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._NgControlStatus_42_7.context; }
    if (((token === import18.ButtonRadioDirective) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._ButtonRadioDirective_45_3.context; }
    if (((token === import19.NG_VALUE_ACCESSOR) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._NG_VALUE_ACCESSOR_45_4; }
    if (((token === import20.NgModel) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._NgModel_45_5.context; }
    if (((token === import21.NgControl) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._NgControl_45_6; }
    if (((token === import22.NgControlStatus) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._NgControlStatus_45_7.context; }
    if (((token === import10.TemplateRef) && (52 === requestNodeIndex))) { return this._TemplateRef_52_5; }
    if (((token === import11.NgIf) && (52 === requestNodeIndex))) { return this._NgIf_52_6.context; }
    if (((token === import10.TemplateRef) && (54 === requestNodeIndex))) { return this._TemplateRef_54_5; }
    if (((token === import11.NgIf) && (54 === requestNodeIndex))) { return this._NgIf_54_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_12_0_0:any = 'Absolute';
    this._ButtonRadioDirective_12_3.check_btnRadio(currVal_12_0_0,throwOnChange,false);
    this._ButtonRadioDirective_12_3.ngDoCheck(this,this._el_12,throwOnChange);
    const currVal_12_1_0:any = this.parentView.context.timeStartRadioModel;
    this._NgModel_12_5.check_model(currVal_12_1_0,throwOnChange,false);
    this._NgModel_12_5.ngDoCheck(this,this._el_12,throwOnChange);
    this._NgControlStatus_12_7.ngDoCheck(this,this._el_12,throwOnChange);
    const currVal_15_0_0:any = 'Relative';
    this._ButtonRadioDirective_15_3.check_btnRadio(currVal_15_0_0,throwOnChange,false);
    this._ButtonRadioDirective_15_3.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_15_1_0:any = this.parentView.context.timeStartRadioModel;
    this._NgModel_15_5.check_model(currVal_15_1_0,throwOnChange,false);
    this._NgModel_15_5.ngDoCheck(this,this._el_15,throwOnChange);
    this._NgControlStatus_15_7.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_21_0_0:any = (this.parentView.context.timeStartRadioModel === 'Absolute');
    this._NgIf_21_6.check_ngIf(currVal_21_0_0,throwOnChange,false);
    this._NgIf_21_6.ngDoCheck(this,this._anchor_21,throwOnChange);
    const currVal_23_0_0:any = (this.parentView.context.timeStartRadioModel === 'Relative');
    this._NgIf_23_6.check_ngIf(currVal_23_0_0,throwOnChange,false);
    this._NgIf_23_6.ngDoCheck(this,this._anchor_23,throwOnChange);
    const currVal_28_0_0:any = this.parentView.context.timezone;
    this._TypeaheadComponent_28_3.check_value(currVal_28_0_0,throwOnChange,false);
    const currVal_28_0_1:any = this.parentView.context.items;
    this._TypeaheadComponent_28_3.check_typeaheadSource(currVal_28_0_1,throwOnChange,false);
    const currVal_28_0_2:any = 0;
    this._TypeaheadComponent_28_3.check_typeaheadMinLength(currVal_28_0_2,throwOnChange,false);
    const currVal_28_0_3:any = 10;
    this._TypeaheadComponent_28_3.check_typeaheadOptionsLimit(currVal_28_0_3,throwOnChange,false);
    const currVal_28_0_4:any = 'Browser time zone';
    this._TypeaheadComponent_28_3.check_placeholder(currVal_28_0_4,throwOnChange,false);
    this._TypeaheadComponent_28_3.ngDoCheck(this,this._el_28,throwOnChange);
    const currVal_42_0_0:any = 'Absolute';
    this._ButtonRadioDirective_42_3.check_btnRadio(currVal_42_0_0,throwOnChange,false);
    const currVal_42_0_1:any = '';
    this._ButtonRadioDirective_42_3.check_uncheckable(currVal_42_0_1,throwOnChange,false);
    this._ButtonRadioDirective_42_3.ngDoCheck(this,this._el_42,throwOnChange);
    const currVal_42_1_0:any = this.parentView.context.timeEndRadioModel;
    this._NgModel_42_5.check_model(currVal_42_1_0,throwOnChange,false);
    this._NgModel_42_5.ngDoCheck(this,this._el_42,throwOnChange);
    this._NgControlStatus_42_7.ngDoCheck(this,this._el_42,throwOnChange);
    const currVal_45_0_0:any = 'Relative';
    this._ButtonRadioDirective_45_3.check_btnRadio(currVal_45_0_0,throwOnChange,false);
    const currVal_45_0_1:any = '';
    this._ButtonRadioDirective_45_3.check_uncheckable(currVal_45_0_1,throwOnChange,false);
    this._ButtonRadioDirective_45_3.ngDoCheck(this,this._el_45,throwOnChange);
    const currVal_45_1_0:any = this.parentView.context.timeEndRadioModel;
    this._NgModel_45_5.check_model(currVal_45_1_0,throwOnChange,false);
    this._NgModel_45_5.ngDoCheck(this,this._el_45,throwOnChange);
    this._NgControlStatus_45_7.ngDoCheck(this,this._el_45,throwOnChange);
    const currVal_52_0_0:any = (this.parentView.context.timeEndRadioModel === 'Absolute');
    this._NgIf_52_6.check_ngIf(currVal_52_0_0,throwOnChange,false);
    this._NgIf_52_6.ngDoCheck(this,this._anchor_52,throwOnChange);
    const currVal_54_0_0:any = (this.parentView.context.timeEndRadioModel === 'Relative');
    this._NgIf_54_6.check_ngIf(currVal_54_0_0,throwOnChange,false);
    this._NgIf_54_6.ngDoCheck(this,this._anchor_54,throwOnChange);
    this._vc_21.detectChangesInNestedViews(throwOnChange);
    this._vc_23.detectChangesInNestedViews(throwOnChange);
    this._vc_52.detectChangesInNestedViews(throwOnChange);
    this._vc_54.detectChangesInNestedViews(throwOnChange);
    this._ButtonRadioDirective_12_3.checkHost(this,this,this._el_12,throwOnChange);
    this._NgControlStatus_12_7.checkHost(this,this,this._el_12,throwOnChange);
    this._ButtonRadioDirective_15_3.checkHost(this,this,this._el_15,throwOnChange);
    this._NgControlStatus_15_7.checkHost(this,this,this._el_15,throwOnChange);
    this._ButtonRadioDirective_42_3.checkHost(this,this,this._el_42,throwOnChange);
    this._NgControlStatus_42_7.checkHost(this,this,this._el_42,throwOnChange);
    this._ButtonRadioDirective_45_3.checkHost(this,this,this._el_45,throwOnChange);
    this._NgControlStatus_45_7.checkHost(this,this,this._el_45,throwOnChange);
    this.compView_28.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_21.destroyNestedViews();
    this._vc_23.destroyNestedViews();
    this._vc_52.destroyNestedViews();
    this._vc_54.destroyNestedViews();
    this.compView_28.destroy();
    this._NgModel_12_5.ngOnDestroy();
    this._NgModel_15_5.ngOnDestroy();
    this._TypeaheadComponent_28_3.ngOnDestroy();
    this._NgModel_42_5.ngOnDestroy();
    this._NgModel_45_5.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 21)) { return new View_TimeRangeComponent2(this.viewUtils,this,21,this._anchor_21,this._vc_21); }
    if ((nodeIndex == 23)) { return new View_TimeRangeComponent3(this.viewUtils,this,23,this._anchor_23,this._vc_23); }
    if ((nodeIndex == 52)) { return new View_TimeRangeComponent4(this.viewUtils,this,52,this._anchor_52,this._vc_52); }
    if ((nodeIndex == 54)) { return new View_TimeRangeComponent5(this.viewUtils,this,54,this._anchor_54,this._vc_54); }
    return (null as any);
  }
  handleEvent_12(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._ButtonRadioDirective_12_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.timeStartRadioModel = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'ngModelChange')) {
      const pd_sub_1:any = ((<any>this.parentView.context.onRadioClick('start')) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
  handleEvent_15(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._ButtonRadioDirective_15_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.timeStartRadioModel = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'ngModelChange')) {
      const pd_sub_1:any = ((<any>this.parentView.context.onRadioClick('start')) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
  handleEvent_28(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'typeaheadOnSelect')) {
      this.parentView.context.timezone = this._TypeaheadComponent_28_3.context.value;
      const pd_sub_0:any = ((<any>this.parentView.context.timezoneChange.emit(this.parentView.context.timezone)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'blur')) {
      const pd_sub_1:any = ((<any>this.parentView.context.onTimezoneBlur(this._TypeaheadComponent_28_3.context)) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
  handleEvent_42(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._ButtonRadioDirective_42_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.timeEndRadioModel = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'ngModelChange')) {
      const pd_sub_1:any = ((<any>this.parentView.context.onRadioClick('end')) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
  handleEvent_45(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._ButtonRadioDirective_45_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.timeEndRadioModel = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'ngModelChange')) {
      const pd_sub_1:any = ((<any>this.parentView.context.onRadioClick('end')) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
}
class View_TimeRangeComponent2 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import23.DateTimePickerComponent>;
  _DateTimePickerComponent_0_3:import24.Wrapper_DateTimePickerComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import8.ViewContainer) {
    super(View_TimeRangeComponent2,renderType_TimeRangeComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'kairos-datetimepicker',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import24.View_DateTimePickerComponent0(this.viewUtils,this,0,this._el_0);
    this._DateTimePickerComponent_0_3 = new import24.Wrapper_DateTimePickerComponent();
    this.compView_0.create(this._DateTimePickerComponent_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'timestampChange',(null as any)),this.eventHandler(this.handleEvent_0));
    this._DateTimePickerComponent_0_3.subscribe(this,this.eventHandler(this.handleEvent_0),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.DateTimePickerComponent) && (0 === requestNodeIndex))) { return this._DateTimePickerComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.parentView.parentView.context.startAbsolute;
    this._DateTimePickerComponent_0_3.check_timestamp(currVal_0_0_0,throwOnChange,false);
    const currVal_0_0_1:any = this.parentView.parentView.context.timezone;
    this._DateTimePickerComponent_0_3.check_timezone(currVal_0_0_1,throwOnChange,false);
    this._DateTimePickerComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._DateTimePickerComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'timestampChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.parentView.context.startAbsolute = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'timestampChange')) {
      const pd_sub_1:any = ((<any>this.parentView.parentView.context.startAbsoluteChange.emit($event)) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
}
class View_TimeRangeComponent3 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import25.RelativePickerComponent>;
  _RelativePickerComponent_0_3:import26.Wrapper_RelativePickerComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import8.ViewContainer) {
    super(View_TimeRangeComponent3,renderType_TimeRangeComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'kairos-relativepicker',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import26.View_RelativePickerComponent0(this.viewUtils,this,0,this._el_0);
    this._RelativePickerComponent_0_3 = new import26.Wrapper_RelativePickerComponent();
    this.compView_0.create(this._RelativePickerComponent_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'modelChange',(null as any)),this.eventHandler(this.handleEvent_0));
    this._RelativePickerComponent_0_3.subscribe(this,this.eventHandler(this.handleEvent_0),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import25.RelativePickerComponent) && (0 === requestNodeIndex))) { return this._RelativePickerComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.parentView.parentView.context.startRelative;
    this._RelativePickerComponent_0_3.check_model(currVal_0_0_0,throwOnChange,false);
    this._RelativePickerComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._RelativePickerComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'modelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.parentView.context.startRelative = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'modelChange')) {
      const pd_sub_1:any = ((<any>this.parentView.parentView.context.startRelativeChange.emit($event)) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
}
class View_TimeRangeComponent4 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import23.DateTimePickerComponent>;
  _DateTimePickerComponent_0_3:import24.Wrapper_DateTimePickerComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import8.ViewContainer) {
    super(View_TimeRangeComponent4,renderType_TimeRangeComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'kairos-datetimepicker',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import24.View_DateTimePickerComponent0(this.viewUtils,this,0,this._el_0);
    this._DateTimePickerComponent_0_3 = new import24.Wrapper_DateTimePickerComponent();
    this.compView_0.create(this._DateTimePickerComponent_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'timestampChange',(null as any)),this.eventHandler(this.handleEvent_0));
    this._DateTimePickerComponent_0_3.subscribe(this,this.eventHandler(this.handleEvent_0),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.DateTimePickerComponent) && (0 === requestNodeIndex))) { return this._DateTimePickerComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.parentView.parentView.context.endAbsolute;
    this._DateTimePickerComponent_0_3.check_timestamp(currVal_0_0_0,throwOnChange,false);
    const currVal_0_0_1:any = this.parentView.parentView.context.timezone;
    this._DateTimePickerComponent_0_3.check_timezone(currVal_0_0_1,throwOnChange,false);
    this._DateTimePickerComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._DateTimePickerComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'timestampChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.parentView.context.endAbsolute = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'timestampChange')) {
      const pd_sub_1:any = ((<any>this.parentView.parentView.context.endAbsoluteChange.emit($event)) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
}
class View_TimeRangeComponent5 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import25.RelativePickerComponent>;
  _RelativePickerComponent_0_3:import26.Wrapper_RelativePickerComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import8.ViewContainer) {
    super(View_TimeRangeComponent5,renderType_TimeRangeComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'kairos-relativepicker',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import26.View_RelativePickerComponent0(this.viewUtils,this,0,this._el_0);
    this._RelativePickerComponent_0_3 = new import26.Wrapper_RelativePickerComponent();
    this.compView_0.create(this._RelativePickerComponent_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'modelChange',(null as any)),this.eventHandler(this.handleEvent_0));
    this._RelativePickerComponent_0_3.subscribe(this,this.eventHandler(this.handleEvent_0),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import25.RelativePickerComponent) && (0 === requestNodeIndex))) { return this._RelativePickerComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.parentView.parentView.context.endRelative;
    this._RelativePickerComponent_0_3.check_model(currVal_0_0_0,throwOnChange,false);
    this._RelativePickerComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._RelativePickerComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'modelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.parentView.context.endRelative = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'modelChange')) {
      const pd_sub_1:any = ((<any>this.parentView.parentView.context.endRelativeChange.emit($event)) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
}
class View_TimeRangeComponent6 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import8.ViewContainer) {
    super(View_TimeRangeComponent6,renderType_TimeRangeComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray4(4,'class','alert alert-danger','role','alert'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Invalid time range in Query Json. ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'Click here to fix!',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ),[disposable_0]);
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.fixInvalid()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}