/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './time-range.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/forms/src/directives';
import * as import4 from '@angular/forms/src/form_providers';
import * as import5 from 'ng2-bootstrap/components/datepicker/datepicker.module';
import * as import6 from 'ng2-bootstrap/components/alert/alert.module';
import * as import7 from 'ng2-bootstrap/components/buttons/buttons.module';
import * as import8 from 'ng2-bootstrap/components/typeahead/typeahead.module';
import * as import9 from '../shared/shared.module';
import * as import10 from '@angular/common/src/localization';
import * as import11 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import12 from 'ng2-bootstrap/components/utils/components-helper.service';
import * as import13 from '@angular/core/src/di/injector';
import * as import14 from '../../node_modules/ng2-bootstrap/components/typeahead/typeahead-container.component.ngfactory';
import * as import15 from '@angular/core/src/i18n/tokens';
import * as import16 from '@angular/core/src/application_ref';
class TimeRangeModuleInjector extends import0.NgModuleInjector<import1.TimeRangeModule> {
  _CommonModule_0:import2.CommonModule;
  _InternalFormsSharedModule_1:import3.InternalFormsSharedModule;
  _FormsModule_2:import4.FormsModule;
  _DatepickerModule_3:import5.DatepickerModule;
  _AlertModule_4:import6.AlertModule;
  _ButtonsModule_5:import7.ButtonsModule;
  _TypeaheadModule_6:import8.TypeaheadModule;
  _SharedModule_7:import9.SharedModule;
  _TimeRangeModule_8:import1.TimeRangeModule;
  __NgLocalization_9:import10.NgLocaleLocalization;
  __RadioControlRegistry_10:import11.RadioControlRegistry;
  __ComponentsHelper_11:import12.ComponentsHelper;
  constructor(parent:import13.Injector) {
    super(parent,[import14.TypeaheadContainerComponentNgFactory],([] as any[]));
  }
  get _NgLocalization_9():import10.NgLocaleLocalization {
    if ((this.__NgLocalization_9 == null)) { (this.__NgLocalization_9 = new import10.NgLocaleLocalization(this.parent.get(import15.LOCALE_ID))); }
    return this.__NgLocalization_9;
  }
  get _RadioControlRegistry_10():import11.RadioControlRegistry {
    if ((this.__RadioControlRegistry_10 == null)) { (this.__RadioControlRegistry_10 = new import11.RadioControlRegistry()); }
    return this.__RadioControlRegistry_10;
  }
  get _ComponentsHelper_11():import12.ComponentsHelper {
    if ((this.__ComponentsHelper_11 == null)) { (this.__ComponentsHelper_11 = new import12.ComponentsHelper(this.parent.get(import16.ApplicationRef),this,this)); }
    return this.__ComponentsHelper_11;
  }
  createInternal():import1.TimeRangeModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._InternalFormsSharedModule_1 = new import3.InternalFormsSharedModule();
    this._FormsModule_2 = new import4.FormsModule();
    this._DatepickerModule_3 = new import5.DatepickerModule();
    this._AlertModule_4 = new import6.AlertModule();
    this._ButtonsModule_5 = new import7.ButtonsModule();
    this._TypeaheadModule_6 = new import8.TypeaheadModule();
    this._SharedModule_7 = new import9.SharedModule();
    this._TimeRangeModule_8 = new import1.TimeRangeModule();
    return this._TimeRangeModule_8;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_1; }
    if ((token === import4.FormsModule)) { return this._FormsModule_2; }
    if ((token === import5.DatepickerModule)) { return this._DatepickerModule_3; }
    if ((token === import6.AlertModule)) { return this._AlertModule_4; }
    if ((token === import7.ButtonsModule)) { return this._ButtonsModule_5; }
    if ((token === import8.TypeaheadModule)) { return this._TypeaheadModule_6; }
    if ((token === import9.SharedModule)) { return this._SharedModule_7; }
    if ((token === import1.TimeRangeModule)) { return this._TimeRangeModule_8; }
    if ((token === import10.NgLocalization)) { return this._NgLocalization_9; }
    if ((token === import11.RadioControlRegistry)) { return this._RadioControlRegistry_10; }
    if ((token === import12.ComponentsHelper)) { return this._ComponentsHelper_11; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const TimeRangeModuleNgFactory:import0.NgModuleFactory<import1.TimeRangeModule> = new import0.NgModuleFactory(TimeRangeModuleInjector,import1.TimeRangeModule);